# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - run: npm ci
            - run: npm run build --if-present
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: npm test
    release:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - run: npx semantic-release
