# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Test
              run: npm run test
    release:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Test
              run: npm run test
            - name: Report Coverage
              run: cat ./coverage/lcov.info | npx coveralls
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
